spring:
  application:
    name: "auth-service"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smeuserdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "638CBE3A90E0303BF3808F40F95A7F02A24B4B5D029C954CF553F79E9EF1DC0384BE681C249F1223F6B55AA21DC070914834CA22C8DD98E14A872CA010091ACC"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#endpoints:
#  shutdown:
#    enabled: true

#eureka:
#  #  instance:
#  #    preferIpAddress: true
#  instance:
#    hostname: localhost
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8060/eureka/

info:
  app:
    name: "authentication-service"
    description: "Authentication Service for SME Prod"

server:
  port: 9898
