spring:
  application:
    name: "projects service"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectsdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

endpoints:
  shutdown:
    enabled: true


server:
  port: 8040